// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vmagg_min_tb.cpp"
#include "Vmagg_min_tb___024root__DepSet_h3b8eec0e__0.cpp"
#include "Vmagg_min_tb___024root__DepSet_h28b89332__0.cpp"
#include "Vmagg_min_tb__main.cpp"
#include "Vmagg_min_tb__Trace__0.cpp"
#include "Vmagg_min_tb___024root__Slow.cpp"
#include "Vmagg_min_tb___024root__DepSet_h3b8eec0e__0__Slow.cpp"
#include "Vmagg_min_tb___024root__DepSet_h28b89332__0__Slow.cpp"
#include "Vmagg_min_tb__Syms.cpp"
#include "Vmagg_min_tb__Trace__0__Slow.cpp"
#include "Vmagg_min_tb__TraceDecls__0__Slow.cpp"
