// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VS1new_tb.cpp"
#include "VS1new_tb___024root__DepSet_h92235bd2__0.cpp"
#include "VS1new_tb___024root__DepSet_h57cde47c__0.cpp"
#include "VS1new_tb__main.cpp"
#include "VS1new_tb__Trace__0.cpp"
#include "VS1new_tb___024root__Slow.cpp"
#include "VS1new_tb___024root__DepSet_h92235bd2__0__Slow.cpp"
#include "VS1new_tb___024root__DepSet_h57cde47c__0__Slow.cpp"
#include "VS1new_tb__Syms.cpp"
#include "VS1new_tb__Trace__0__Slow.cpp"
#include "VS1new_tb__TraceDecls__0__Slow.cpp"
