// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VSommatore_tb.cpp"
#include "VSommatore_tb___024root__DepSet_hb50a21fd__0.cpp"
#include "VSommatore_tb___024root__DepSet_h4adfa080__0.cpp"
#include "VSommatore_tb__main.cpp"
#include "VSommatore_tb__Trace__0.cpp"
#include "VSommatore_tb___024root__Slow.cpp"
#include "VSommatore_tb___024root__DepSet_hb50a21fd__0__Slow.cpp"
#include "VSommatore_tb___024root__DepSet_h4adfa080__0__Slow.cpp"
#include "VSommatore_tb__Syms.cpp"
#include "VSommatore_tb__Trace__0__Slow.cpp"
#include "VSommatore_tb__TraceDecls__0__Slow.cpp"
