// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vstato3tb.cpp"
#include "Vstato3tb___024root__DepSet_h1b953afc__0.cpp"
#include "Vstato3tb___024root__DepSet_h4622fbb5__0.cpp"
#include "Vstato3tb__main.cpp"
#include "Vstato3tb__Trace__0.cpp"
#include "Vstato3tb___024root__Slow.cpp"
#include "Vstato3tb___024root__DepSet_h1b953afc__0__Slow.cpp"
#include "Vstato3tb___024root__DepSet_h4622fbb5__0__Slow.cpp"
#include "Vstato3tb__Syms.cpp"
#include "Vstato3tb__Trace__0__Slow.cpp"
#include "Vstato3tb__TraceDecls__0__Slow.cpp"
