// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vstato4tb.cpp"
#include "Vstato4tb___024root__DepSet_h2f25c1e9__0.cpp"
#include "Vstato4tb___024root__DepSet_hff10620b__0.cpp"
#include "Vstato4tb__main.cpp"
#include "Vstato4tb__Trace__0.cpp"
#include "Vstato4tb___024root__Slow.cpp"
#include "Vstato4tb___024root__DepSet_h2f25c1e9__0__Slow.cpp"
#include "Vstato4tb___024root__DepSet_hff10620b__0__Slow.cpp"
#include "Vstato4tb__Syms.cpp"
#include "Vstato4tb__Trace__0__Slow.cpp"
#include "Vstato4tb__TraceDecls__0__Slow.cpp"
