// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vtb_Stato1.cpp"
#include "Vtb_Stato1___024root__DepSet_hc46b3c68__0.cpp"
#include "Vtb_Stato1___024root__DepSet_h4e92ebc1__0.cpp"
#include "Vtb_Stato1__main.cpp"
#include "Vtb_Stato1__Trace__0.cpp"
#include "Vtb_Stato1___024root__Slow.cpp"
#include "Vtb_Stato1___024root__DepSet_hc46b3c68__0__Slow.cpp"
#include "Vtb_Stato1___024root__DepSet_h4e92ebc1__0__Slow.cpp"
#include "Vtb_Stato1__Syms.cpp"
#include "Vtb_Stato1__Trace__0__Slow.cpp"
#include "Vtb_Stato1__TraceDecls__0__Slow.cpp"
